baseurl = "http://me.shenoy/"
languageCode = "en-us"
title = "Rajesh Shenoy"
theme = "mysore"

[params]
author = "Rajesh Shenoy"
twitter = "brshenoy"
facebook = "brshenoy"
github = "shenoybr"
instagram = "brshenoy"
linkedin = "brshenoy"

[[menu.side]]
name = "About"
identifier = "about"
weight = -100
url = "/about/"

