name = "Mysore"
license = "MIT"
licenselink = "http://opensource.org/licenses/MIT"
description = "Minimalistic theme for Hugo"
homepage = "http://rajesh.shenoy.me"
tags = ["Blog", "Golang", "Development"]
features = ["", ""]

[author]
  name = "Rajesh Shenoy"
  homepage = "http://rajesh.shenoy.me"

# If porting an existing theme
[original]
  name = "Rajesh Shenoy"
  homepage = "http://rajesh.shenoy.me"
  repo = "https://github.com/shenoybr/mysore"
